# Generated by Django 3.2 on 2021-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_auto_20210521_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, null=True)),
                ('jobdescription', models.CharField(max_length=15, null=True)),
                ('vaccany', models.IntegerField()),
            ],
        ),
    ]
