# Generated by Django 3.2 on 2021-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobdescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
